name: iOS CI Pipeline
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build and test
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

    - name: Show current version of Xcode
      run: xcodebuild -version

    - name: List available devices
      run: xcrun simctl list devices

    - name: Select the first available simulator
      id: select_simulator
      run: |
        # List available simulators that are available and not in shutdown state
        SIMULATOR=$(xcrun simctl list devices available | grep -E 'iPhone.*\(\S+\) \(\w+\)' | grep -v "Shutdown" | head -n 1)

        # If no simulator is found, exit
        if [[ -z "$SIMULATOR" ]]; then
          echo "No available simulators found"
          exit 1
        fi

        # Extract the simulator name and OS version from the output
        SIMULATOR_NAME=$(echo $SIMULATOR | sed -E 's/([A-Za-z0-9 ]+) \([A-Za-z0-9-]*\) \((.*)\)/\1/')
        SIMULATOR_OS=$(echo $SIMULATOR | sed -E 's/([A-Za-z0-9 ]+) \([A-Za-z0-9-]*\) \((.*)\)/\2/')

        echo "Selected simulator: $SIMULATOR_NAME with iOS $SIMULATOR_OS"

        # Set the simulator name and OS version as outputs
        echo "::set-output name=simulator_name::$SIMULATOR_NAME"
        echo "::set-output name=simulator_os::$SIMULATOR_OS"

    - name: Debug selected simulator
      run: |
        echo "Selected simulator: $SIMULATOR_NAME with iOS $SIMULATOR_OS"
        # Check the available simulators again to verify if the selected one exists
        xcrun simctl list devices

    - name: Boot the selected simulator
      run: |
        # Boot the selected simulator
        xcrun simctl boot "$SIMULATOR_NAME"
        # Wait for the simulator to finish booting
        sleep 10

    - name: Build and run tests
      run: |
        # Retrieve simulator name and OS version from the previous step
        SIMULATOR_NAME="${{ steps.select_simulator.outputs.simulator_name }}"
        SIMULATOR_OS="${{ steps.select_simulator.outputs.simulator_os }}"

        # Run the tests using xcodebuild
        xcodebuild clean test \
          -scheme "WeatherTests" \
          -destination "platform=iOS Simulator,name=$SIMULATOR_NAME,OS=$SIMULATOR_OS" \
          -quiet \
          -enableCodeCoverage YES

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
