name: iOS CI Pipeline
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: config environment
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.1.0.app/Contents/Developer
    - name: Show current version of Xcode
      run: xcodebuild -version

  test:
    name: run unit tests and ui tests
    runs-on: macos-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.1.0.app/Contents/Developer
    - name: Show current version of Xcode
      run: xcodebuild -version
    - name: Run Unit and UI Tests
      run: |
        # Ejecutar pruebas unitarias con cobertura habilitada
        xcodebuild test \
          -scheme WeatherTests \
          -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16' \
          -enableCodeCoverage YES \
          -resultBundlePath result_bundle_unit.xcresult

        # Ejecutar pruebas de UI con cobertura habilitada
        xcodebuild test \
          -scheme WeatherUITests \
          -destination 'platform=iOS Simulator,OS=latest,name=iPhone 16' \
          -enableCodeCoverage YES \
          -resultBundlePath result_bundle_ui.xcresult

    - name: Extract coverage from .xcresult and generate JSON
      run: |
        # Extraer el archivo de cobertura en formato JSON
        xcrun xcresulttool get --legacy --path result_bundle_unit.xcresult --format json > result_unit.json
        xcrun xcresulttool get --legacy --path result_bundle_ui.xcresult --format json > result_ui.json

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: |
          result_unit.json
          result_ui.json
        slug: ronaldfabra/Weather
