name: iOS CI Pipeline
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build and test
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

    - name: Show current version of Xcode
      run: xcodebuild -version

    - name: List available devices
      run: xcrun simctl list devices

    - name: Build and run tests
      run: |
        xcodebuild clean test \
          -scheme "WeatherTests" \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
          -enableCodeCoverage YES

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
